config/routes.rb
Rails.application.routes.draw do
  #get 'twets/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'twets#new'
  resources :twets do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twet.rb
class Twet < ApplicationRecord
  validates :content, presence: true, length:{in:1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/twets_controller.rb
class TwetsController < ApplicationController
  before_action :set_twet, only: [:show, :edit, :update, :destroy]
  def index
    @twets = Twet.all
  end

  def new
    @twet = Twet.new
  end

  def create
    @twet = Twet.new(twet_params)
    if params[:back]
      render :new
    else
      if @twet.save
        redirect_to twets_path, notice: "投稿しました！"
      else
        render "new"
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @twet.update(twet_params)
      redirect_to twets_path, notice: "編集しました！"
    else
      render 'edit'
    end
  end

  def confirm
    @twet = Twet.new(twet_params)
    render :new if @twet.invalid?
  end

  def destroy
    @twet.destroy
    redirect_to twets_path, notice:"削除しました！"
  end

  private

  def twet_params
    params.require(:twet).permit(:content)
  end

  def set_twet
    @twet = Twet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twets_helper.rb
module TwetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
        confirm_twets_path
    elsif action_name == 'edit'
        twet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tw_Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name= "viewport" content="width"=device-width>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class = "navbar navbar-default">
        <div class = "container-fluid">
          <a class="navbar-brand" href="/twets/new">Twets</a>
            <ul class="nav navbar-nav">
            </ul>
        </div>
      </nav>
    </header>
      <div class = "img">
        <%= image_tag 'images.jpg', :size =>'100x100' %>
      </div class = "img">
    <%= yield %>

    <footer>
      <p>運営会社DIVE INTO CODE</p>
      <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
    </footer>  
  </body>
</html>

app/views/twets/_form.html.erb
<%= form_with(model: @twet, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @twet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @twet.errors.count %>エラーがあります。</h2>

      <ul>
        <% @twet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="container">
   <%= form.label :content %>
   <%= form.text_field :content %>
 </div>
 <%= form.submit %>
<% end %>

<%= link_to "一覧画面にもどる", twets_path, class: 'btn btn-success' %>

app/views/twets/confirm.html.erb
<h3>以下の内容でツイートする</h3>

<%= form_with(model: @twet, url: twets_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @twet.content %></p>

  <%= form.submit "ツイートする" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/twets/edit.html.erb
<%= render 'form' %>

app/views/twets/index.html.erb
  <h3><%= notice %></h3>
  <br>
  <div class = "new">
  <%= link_to '新規投稿画面',new_twet_path, class: 'btn btn-success' %>
  </div>
  <div class="container">
    <h1>つぶやき一覧</h1>
  <% @twets.each do |twet| %>
    <div class= "panel">
      <p><%= twet.content %></p>
        <div class = "link">
        <%= link_to "編集します！", edit_twet_path(twet.id), data:{confirm: "本当に編集していいですか？"} %>
        <%= link_to "削除します！", twet_path(twet.id), method: :delete, data:{confirm: "本当に削除していいですか？"} %>
        </div>
    </div>
  <% end %>
  </div>
  


  

  

app/views/twets/new.html.erb
<div class='container'>
  <h2>ツイートする</h2>
</div>

<%= render 'form' %>

app/views/twets/show.html.erb
<%= render 'form' %>